name: py39deezy
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.9.12
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
      - absl-py==1.2.0
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==2.0.5
      - attrs==21.4.0
      - backcall==0.2.0
      - beautifulsoup4==4.11.1
      - bleach==5.0.1
      - cachetools==5.2.0
      - cffi==1.15.1
      - charset-normalizer==2.1.0
      - click==8.1.3
      - cycler==0.11.0
      - debugpy==1.6.2
      - decorator==5.1.1
      - deezymatch==1.3.3
      - defusedxml==0.7.1
      - entrypoints==0.4
      - executing==0.9.0
      - faiss-cpu==1.7.2
      - fastjsonschema==2.16.1
      - fonttools==4.34.4
      - gensim==4.2.0
      - google-auth==2.9.1
      - google-auth-oauthlib==0.4.6
      - grpcio==1.47.0
      - idna==3.3
      - importlib-metadata==4.12.0
      - ipykernel==6.15.1
      - ipython==8.4.0
      - ipython-genutils==0.2.0
      - ipython-sparql-pandas==1.4
      - ipywidgets==7.7.1
      - isodate==0.6.1
      - jedi==0.18.1
      - jinja2==3.1.2
      - joblib==1.1.0
      - jsonschema==4.7.2
      - jupyter-client==7.3.4
      - jupyter-core==4.11.1
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==1.1.1
      - kiwisolver==1.4.4
      - markdown==3.4.1
      - markupsafe==2.1.1
      - matplotlib==3.5.2
      - matplotlib-inline==0.1.3
      - mistune==0.8.4
      - nbclient==0.6.6
      - nbconvert==6.5.0
      - nbformat==5.4.0
      - nest-asyncio==1.5.5
      - nltk==3.7
      - notebook==6.4.12
      - numpy==1.23.1
      - oauthlib==3.2.0
      - packaging==21.3
      - pandas==1.4.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.2.0
      - prometheus-client==0.14.1
      - prompt-toolkit==3.0.30
      - protobuf==3.19.4
      - psutil==5.9.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
      - pygments==2.12.0
      - pyparsing==3.0.9
      - pyrsistent==0.18.1
      - python-dateutil==2.8.2
      - pytz==2022.1
      - pyyaml==6.0
      - pyzmq==23.2.0
      - rdflib==6.2.0
      - regex==2022.7.25
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.1.1
      - scipy==1.8.1
      - send2trash==1.8.0
      - six==1.16.0
      - smart-open==6.0.0
      - soupsieve==2.3.2.post1
      - sparqlwrapper==2.0.0
      - stack-data==0.3.0
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - terminado==0.15.0
      - thefuzz==0.19.0
      - threadpoolctl==3.1.0
      - tinycss2==1.1.1
      - torch==1.12.0
      - torchvision==0.13.0
      - tornado==6.2
      - tqdm==4.64.0
      - traitlets==5.3.0
      - typing-extensions==4.3.0
      - urllib3==1.26.11
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - werkzeug==2.2.0
      - widgetsnbextension==3.6.1
      - zipp==3.8.1
